/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class controllers_TestWithNativeLibrary */

#ifndef _Included_controllers_TestWithNativeLibrary
#define _Included_controllers_TestWithNativeLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     controllers_TestWithNativeLibrary
 * Method:    init
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_controllers_TestWithNativeLibrary_init
  (JNIEnv *, jobject, jstring);

/*
 * Class:     controllers_TestWithNativeLibrary
 * Method:    add_vec
 * Signature: ([I[I[I)V
 */
JNIEXPORT void JNICALL Java_controllers_TestWithNativeLibrary_add_1vec
  (JNIEnv *, jobject, jintArray, jintArray, jintArray);

/*
 * Class:     controllers_TestWithNativeLibrary
 * Method:    clear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_controllers_TestWithNativeLibrary_clear
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
