/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class AxonerveWordcount */

#ifndef _Included_AxonerveWordcount
#define _Included_AxonerveWordcount
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     AxonerveWordcount
 * Method:    init
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_AxonerveWordcount_init
  (JNIEnv *, jobject, jstring);

/*
 * Class:     AxonerveWordcount
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_AxonerveWordcount_close
  (JNIEnv *, jobject);

/*
 * Class:     AxonerveWordcount
 * Method:    reset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_AxonerveWordcount_reset
  (JNIEnv *, jobject);

/*
 * Class:     AxonerveWordcount
 * Method:    doWordCount
 * Signature: ([C)V
 */
JNIEXPORT void JNICALL Java_AxonerveWordcount_doWordCount
  (JNIEnv *, jobject, jcharArray);

/*
 * Class:     AxonerveWordcount
 * Method:    getResult
 * Signature: ([I[I)V
 */
JNIEXPORT void JNICALL Java_AxonerveWordcount_getResult
  (JNIEnv *, jobject, jintArray, jintArray);

/*
 * Class:     AxonerveWordcount
 * Method:    clear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_AxonerveWordcount_clear
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
